#!/usr/bin/perl


$AS="/usr/bin/as.bin";
$TRANS="/usr/bin/rr-translate";

$env=delete $ENV{"ASM_SUBST_DIR"};
exec $AS, @ARGV unless $env;

$input=pop(@ARGV);

$opt=delete $ENV{"ASM_SUBST_OPT"};
$opt{$1}++ while $opt =~ s#\-(\w)\s*##x;

# print STDERR "OPTIONS: ", join(", ", keys %opt),"\n";

$cmd= "set -o pipefail && ";

( $INCDIR=readlink($TRANS) ) =~ s{/[^/]+$}{};

{
	$tmp="/tmp/a1-$$.S";
# we need to support "-" as input, too - so a simply "cp" doesn't work.

	$cmd .= " cat $input > $tmp && ".
# Remove #APP and similar, to avoid getting high-level source like 
# "static inline", "while ()", "#define" etc. getting in the way.
	" grep -v '^#' < $tmp | " .
	($opt{"M"} ? "" : 
# ASM macros are now done via "as", previously via 
# " gcc " . $ENV{"COLLECT_GCC_OPTIONS"} . " -S $tmp | " .
		" $AS -alm -o /dev/null - | " .
		($opt{"D"} ? " tee /tmp/a2-$$.s | " : "") ) .
# The actual translation
	" PERL5LIB=$INCDIR $TRANS " . 
	($opt{"d"} ? "-D " : "") .
	" -s" . $env . " - " .
	($opt{"D"} ? " | tee /tmp/a3-$$.s " : "") .
	"| ";

	$input="-";
}

$cmd .= join(" ", $AS, @ARGV, $input);

if ($opt{"D"})
{
	$cmd .= " && set >> $tmp ; echo '" . join("' '", @ARGV) . "' >> $tmp";
	print STDERR "calling $cmd\n";
}
else
{
	$cmd .= " && rm $tmp";
}

#%ENV=( "PATH" => $ENV{"PATH"} );

exec "bash", "-c", $cmd;

# vim: set sw=4 ts=4 et
